# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  issues:
    types:
      - opened

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: IMAGES
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Display the environment variables and their values
        run: |
          print %ENV
        shell: perl {0}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}



      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          docker pull ${{secrets.IMAGE_NAME}}
          docker tag ${{secrets.IMAGE_NAME}} ${{secrets.DOCKER_USERNAME}}/${{secrets.IMAGE_TAG}}

      

      # Runs a set of commands using the runners shell
      - name: Push to Docker Registry
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/kube-cross:v1.21.0-go1.16.15-buster.0